### ISSUE TITLE
How to ensure estimation signals phases are in common with referenced signal?

### ISSUE THREAD

**Issue by BLi4ee** [JusperLee/Conv-TasNet#59]
if estimation signals are opposite phase to reference signals, the si-snr still decrease. But for communication signals(such as QPSK、BPSK), the opposite phase causes the bit error rate almost 1. How to ensure the same phase between estimation signals and reference signals.

**Comment by JusperLee** [comment]
I understand your concern about the phase issue, especially in the communication domain where opposite phase signals can drastically affect the bit error rate (BER). One possible solution is to calculate the magnitude difference between the estimated and reference signals instead of directly comparing the waveforms. This approach ignores phase mismatches and focuses on the amplitude, which may help mitigate the issue for communication signals like QPSK or BPSK.
